### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by FoxIshDaBest** [TomCreeper/CreepyFreedomBot#1]
@TomCreeper,
There has been a copyright infringement in the following files:
* [_BotUtil.java_] (https://github.com/TomCreeper/CreepyFreedomBot/blob/master/src/com/FoxIshDaBest/FreedomBot/BotUtil.java) under _FB_DEVELOPERS_

Please fix this or I will take further action.
Thanks in advance,
Dylan (FoxIshDaBest)

**Comment by TomCreeper** [comment]
Okay, sorry but i'll like to change it to my server.

**Comment by FoxIshDaBest** [comment]
You may add yourself to the developer list, but you may not remove me since I am the creator of this plugin. @TomCreeper
